title: Blog
description: Notes on various things that Pete comes across
author: Pete Huang
about: Filler
disqus_shortname: 
google_analytics: UA-139581284-1
avatar_url: /static/img/Pete.jpg

enableTags: true
tagarray: []

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/petehuang"

urls:
    - text: About Me
      url: /about/

permalink: /:title

url: "https://peteh.me"
baseurl: ""
#paginate: 20
#per_page: 20
#paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

future: true
